version: 2

models:
    - name: atleast_one_order_completed
      columns:
        - name: customer_id
          tests:
            - unique
            - not_null
        - name: first_name
        - name: last_name
        - name: atleast_one_order_completed
  
    - name: expensive_buyer
      columns:
        - name: customer_id
          tests:
            - unique
            - not_null
        - name: first_name
        - name: last_name
        - name: avg_amt
        - name: expensive_buyer

    - name: atleast_one_order_returned
      columns:
        - name: customer_id
          tests:
            - unique
            - not_null
        - name: first_name
        - name: last_name
        - name: atleast_one_order_returned

        